version: '3.8'

networks:
  backend:

services:
  db:
    container_name: db
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./add-uuid.sql:/docker-entrypoint-initdb.d/add-uuid.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 10
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=PotatoeS123
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports: 
      - 6831:6831/udp
      - 6832:6832/udp
      - 14268:14268
      - 14250:14250
      - 16686:16686
      - 5778:5778
