name: Pull Request Check
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/pull-request.check.yml'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-pull-request-check
  cancel-in-progress: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/backend/projects
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build /p:TreatWarningsAsErrors=true /warnaserror

  # test-backend:  
  #   name: test api
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: backend/tests
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-dotnet@v2
  #       with:
  #         dotnet-version: '6.0.x'
  #     - name: Run tests
  #       run:  dotnet test --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CollectCoverage=true /p:CoverletOutputFormat=json '/p:Exclude="[*]*.Migrations,[*]D3SK.*"' /p:ExcludeByAttribute=\"Migration,DbContext\" /p:CoverletOutput=coverage/lcov
